# Generated by Django 5.2.7 on 2025-10-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='animals/')),
                ('category', models.CharField(choices=[('predator', 'Predator'), ('herbivore', 'Herbivore'), ('omnivore', 'Omnivore'), ('other', 'Other')], default='other', max_length=255)),
                ('habitat', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('lifespan', models.CharField(max_length=255)),
                ('interesting_fact', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marine Animal',
                'verbose_name_plural': 'Marine Animals',
                'ordering': ['category', 'name'],
            },
        ),
    ]
